# Generated by Django 4.2 on 2023-04-20 18:03

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('urlshortner', '0004_alter_urlshortner_short'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('time', models.DateTimeField(auto_now=True)),
                ('timeupdate', models.DateTimeField(auto_now_add=True)),
                ('view_url', models.OneToOneField(on_delete=builtins.any, to='urlshortner.urlshortner')),
            ],
        ),
    ]
