# Generated by Django 4.2 on 2023-04-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortner',
            name='short',
            field=models.CharField(blank=True, default='abc', max_length=15),
        ),
    ]
