# Generated by Django 4.2 on 2023-04-16 14:55

from django.db import migrations, models
import urlshortner.validators


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0002_alter_urlshortner_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortner',
            name='url',
            field=models.CharField(max_length=220, validators=[urlshortner.validators.validate_dot_com, urlshortner.validators.validate_url]),
        ),
    ]
