# Generated by Django 4.2 on 2023-04-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortner', '0003_alter_urlshortner_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshortner',
            name='short',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
